apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer
  namespace: apache-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - image: alexdev2017/kafkaconsumer:1.2
          imagePullPolicy: Always
          name: kafka-producer
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer-service
  namespace: apache-kafka
spec:
  ports:
   - name: kafka-producer-port
     port: 8080
     protocol: TCP
     targetPort: 8080
  selector:
    app: kafka-producer
  type: NodePort